language: node_js
node_js:
  - 8

branches:
  only:
  - master

notifications:
email:
  on_success: change
  on_failure: always

cache:
  directories:
    - node_modules
script:
  - npm install
  - npm run build
  - npm test
  - cd build
  - cp index.html 404.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master